SERIES_REGISTRY = {'global_crude_oil': {'series_id': 'global_crude_oil',
                      'source': 'ceic',
                      'source_key': '42651501',
                      'label': 'Crude Oil',
                      'unit': 'USD/Barrel',
                      'frequency': 'Daily'},
 'global_crude_oil_wti': {'series_id': 'global_crude_oil_wti',
                          'source': 'ceic',
                          'source_key': '42651401',
                          'label': 'Crude Oil: WTI',
                          'unit': 'USD/Barrel',
                          'frequency': 'Daily'},
 'global_us_natural_gas': {'series_id': 'global_us_natural_gas',
                           'source': 'ceic',
                           'source_key': '40780401',
                           'label': 'US Natural Gas',
                           'unit': 'USD/MM BTU',
                           'frequency': 'Daily'},
 'global_germany_natural_gas': {'series_id': 'global_germany_natural_gas',
                                'source': 'ceic',
                                'source_key': '449519797',
                                'label': 'Germany Natural Gas',
                                'unit': 'USD/MM BTU',
                                'frequency': 'Daily'},
 'global_japan_naphtha': {'series_id': 'global_japan_naphtha',
                          'source': 'ceic',
                          'source_key': '161345001',
                          'label': 'Japan Naphtha',
                          'unit': 'USD/Barrel',
                          'frequency': 'Monthly'},
 'global_france_naphtha': {'series_id': 'global_france_naphtha',
                           'source': 'ceic',
                           'source_key': '352664901',
                           'label': 'France Naphtha',
                           'unit': 'USD/Ton',
                           'frequency': 'Monthly'},
 'sea_cargo_handled': {'series_id': 'sea_cargo_handled',
                       'source': 'ceic',
                       'source_key': '36680501',
                       'label': 'Sea Cargo Handled',
                       'unit': 'Ton th',
                       'frequency': 'Monthly'},
 'container_throughput': {'series_id': 'container_throughput',
                          'source': 'ceic',
                          'source_key': '36681201',
                          'label': 'Container Throughput',
                          'unit': 'TEU th',
                          'frequency': 'Monthly'},
 'air_flight_movements': {'series_id': 'air_flight_movements',
                          'source': 'ceic',
                          'source_key': '36670301',
                          'label': 'Flight Movements',
                          'unit': 'Unit',
                          'frequency': 'Monthly'},
 'air_passenger_movements': {'series_id': 'air_passenger_movements',
                             'source': 'ceic',
                             'source_key': '241774802',
                             'label': 'Passenger Movements',
                             'unit': 'Person',
                             'frequency': 'Monthly'},
 'air_freight_movements': {'series_id': 'air_freight_movements',
                           'source': 'ceic',
                           'source_key': '241774902',
                           'label': 'Air Freight Movements',
                           'unit': 'Ton',
                           'frequency': 'Monthly'},
 'financial_sgx_turnover': {'series_id': 'financial_sgx_turnover',
                            'source': 'ceic',
                            'source_key': '35960701',
                            'label': 'SGX Daily Turnover',
                            'unit': 'Share mn',
                            'frequency': 'Daily'},
 'financial_forex_turnover': {'series_id': 'financial_forex_turnover',
                              'source': 'ceic',
                              'source_key': '471805317',
                              'label': 'Forex Monthly Turnover',
                              'unit': 'SGD mn',
                              'frequency': 'Monthly'},
 'financial_sora_3m': {'series_id': 'financial_sora_3m',
                       'source': 'ceic',
                       'source_key': '468026967',
                       'label': 'SORA 3M Compounded',
                       'unit': '% pa',
                       'frequency': 'Daily'},
 'financial_yield_2y': {'series_id': 'financial_yield_2y',
                        'source': 'ceic',
                        'source_key': '35945301',
                        'label': 'MAS Yield 2Y',
                        'unit': '% pa',
                        'frequency': 'Daily'},
 'financial_yield_10y': {'series_id': 'financial_yield_10y',
                         'source': 'ceic',
                         'source_key': '35945601',
                         'label': 'MAS Yield 10Y',
                         'unit': '% pa',
                         'frequency': 'Daily'},
 'visitor_arrival_land': {'series_id': 'visitor_arrival_land',
                          'source': 'ceic',
                          'source_key': '36588001',
                          'label': 'Visitor Arrivals by Land',
                          'unit': 'Person',
                          'frequency': 'Monthly'},
'food_and_beverage_sales': {'series_id': 'food_and_beverage_sales',
                          'source': 'ceic',
                          'source_key': '720061197',
                          'label': 'Food and Beverage Services Value (2025=100)',
                          'unit': 'Index',
                          'frequency': 'Monthly'},
 'singstat_petrol_92': {'series_id': 'singstat_petrol_92',
                        'source': 'ceic',
                        'source_key': '542487397',
                        'label': 'Retail Prices: Petrol, 92 Octane (SingStat)',
                        'unit': 'SGD/Litre',
                        'frequency': 'Monthly'},
 'singstat_petrol_95': {'series_id': 'singstat_petrol_95',
                        'source': 'ceic',
                        'source_key': '542487387',
                        'label': 'Retail Prices: Petrol, 95 Octane (SingStat)',
                        'unit': 'SGD/Litre',
                        'frequency': 'Monthly'},
 'singstat_petrol_98': {'series_id': 'singstat_petrol_98',
                        'source': 'ceic',
                        'source_key': '542487377',
                        'label': 'Retail Prices: Petrol, 98 Octane (SingStat)',
                        'unit': 'SGD/Litre',
                        'frequency': 'Monthly'},
 'singstat_diesel': {'series_id': 'singstat_diesel',
                     'source': 'ceic',
                     'source_key': '542834527',
                     'label': 'Retail Prices: Diesel (SingStat)',
                     'unit': 'SGD/Litre',
                     'frequency': 'Monthly'},
 # SingStat Table Builder — Merchandise Trade By Commodity Section (monthly).
 # Table M451001 carries both imports and exports; the seriesNo path picks
 # the petroleum subtree under imports (2.1.1) vs exports (3.1.1).
 # source_key format: "<tableId>:<seriesNo>".
 'singstat_imports_petroleum': {'series_id': 'singstat_imports_petroleum',
                                'source': 'singstat',
                                'source_key': 'M451001:2.1.1',
                                'label': 'Singapore Imports: Petroleum (SingStat)',
                                'unit': 'SGD Thousand',
                                'frequency': 'Monthly'},
 'singstat_exports_petroleum': {'series_id': 'singstat_exports_petroleum',
                                'source': 'singstat',
                                'source_key': 'M451001:3.1.1',
                                'label': 'Singapore Exports: Petroleum (SingStat)',
                                'unit': 'SGD Thousand',
                                'frequency': 'Monthly'},
 # Construction — Contracts Awarded (Total Public & Private), monthly, SGD Million.
 'singstat_construction_contracts': {'series_id': 'singstat_construction_contracts',
                                     'source': 'singstat',
                                     'source_key': 'M400001:1',
                                     'label': 'Construction Contracts Awarded (Total)',
                                     'unit': 'SGD Million',
                                     'frequency': 'Monthly'},
 # Wholesale Trade Index (2017=100) — Ship Chandlers & Bunkering, quarterly.
 'singstat_wti_bunkering': {'series_id': 'singstat_wti_bunkering',
                            'source': 'singstat',
                            'source_key': 'M601781:11',
                            'label': 'Wholesale Trade Index: Ship Chandlers & Bunkering',
                            'unit': 'Index (2017=100)',
                            'frequency': 'Quarterly'},
 # Wholesale Trade Index (2017=100) — Total excl Petroleum, quarterly.
 'singstat_wti_ex_petroleum': {'series_id': 'singstat_wti_ex_petroleum',
                               'source': 'singstat',
                               'source_key': 'M601781:2',
                               'label': 'Wholesale Trade Index: Total excl Petroleum',
                               'unit': 'Index (2017=100)',
                               'frequency': 'Quarterly'},
 # Electricity Tariff — Low Tension Domestic, monthly, cents/kWh.
 'singstat_electricity_tariff': {'series_id': 'singstat_electricity_tariff',
                                 'source': 'singstat',
                                 'source_key': 'M890991:1',
                                 'label': 'Electricity Tariff: Low Tension Domestic',
                                 'unit': 'Cents/kWh',
                                 'frequency': 'Monthly'},
 # IPI sub-indices from data.gov.sg (source='datagov_ipi')
 'ipi_petrochemicals': {'series_id': 'ipi_petrochemicals',
                        'source': 'datagov_ipi',
                        'source_key': 'Petrochemicals',
                        'label': 'IPI: Petrochemicals',
                        'unit': 'Index (2019=100)',
                        'frequency': 'Monthly'},
 'ipi_petroleum': {'series_id': 'ipi_petroleum',
                   'source': 'datagov_ipi',
                   'source_key': 'Petroleum',
                   'label': 'IPI: Petroleum',
                   'unit': 'Index (2019=100)',
                   'frequency': 'Monthly'},
 'ipi_chemicals_cluster': {'series_id': 'ipi_chemicals_cluster',
                           'source': 'datagov_ipi',
                           'source_key': 'Chemicals Cluster',
                           'label': 'IPI: Chemicals Cluster',
                           'unit': 'Index (2019=100)',
                           'frequency': 'Monthly'},
 'ipi_semiconductors': {'series_id': 'ipi_semiconductors',
                        'source': 'datagov_ipi',
                        'source_key': 'Semiconductors',
                        'label': 'IPI: Semiconductors',
                        'unit': 'Index (2019=100)',
                        'frequency': 'Monthly'},
 # ── Construction Materials — Prices (CEIC, monthly) ──
 'ceic_constr_price_cement': {'series_id': 'ceic_constr_price_cement',
                              'source': 'ceic',
                              'source_key': '222874602',
                              'label': 'Construction Materials Price: Cement',
                              'unit': 'SGD/Ton',
                              'frequency': 'Monthly'},
 'ceic_constr_price_steel': {'series_id': 'ceic_constr_price_steel',
                              'source': 'ceic',
                              'source_key': '222874702',
                              'label': 'Construction Materials Price: Steel Bars',
                              'unit': 'SGD/Ton',
                              'frequency': 'Monthly'},
 'ceic_constr_price_granite': {'series_id': 'ceic_constr_price_granite',
                                'source': 'ceic',
                                'source_key': '222874802',
                                'label': 'Construction Materials Price: Granite',
                                'unit': 'SGD/Ton',
                                'frequency': 'Monthly'},
 'ceic_constr_price_sand': {'series_id': 'ceic_constr_price_sand',
                             'source': 'ceic',
                             'source_key': '222874902',
                             'label': 'Construction Materials Price: Concreting Sand',
                             'unit': 'SGD/Ton',
                             'frequency': 'Monthly'},
 'ceic_constr_price_concrete': {'series_id': 'ceic_constr_price_concrete',
                                 'source': 'ceic',
                                 'source_key': '222875002',
                                 'label': 'Construction Materials Price: Ready-mixed Concrete',
                                 'unit': 'SGD/Cubic Metre',
                                 'frequency': 'Monthly'},
 # ── Construction Materials — Demand (CEIC, monthly) ──
 'ceic_constr_demand_cement': {'series_id': 'ceic_constr_demand_cement',
                                'source': 'ceic',
                                'source_key': '360396397',
                                'label': 'Construction Materials Demand: Cement',
                                'unit': 'Ton th',
                                'frequency': 'Monthly'},
 'ceic_constr_demand_steel': {'series_id': 'ceic_constr_demand_steel',
                               'source': 'ceic',
                               'source_key': '360396407',
                               'label': 'Construction Materials Demand: Steel Bars',
                               'unit': 'Ton th',
                               'frequency': 'Monthly'},
 'ceic_constr_demand_granite': {'series_id': 'ceic_constr_demand_granite',
                                 'source': 'ceic',
                                 'source_key': '360396417',
                                 'label': 'Construction Materials Demand: Granite',
                                 'unit': 'Ton th',
                                 'frequency': 'Monthly'},
 'ceic_constr_demand_concrete': {'series_id': 'ceic_constr_demand_concrete',
                                  'source': 'ceic',
                                  'source_key': '360396427',
                                  'label': 'Construction Materials Demand: Ready-mixed Concrete',
                                  'unit': 'Cubic Metre th',
                                  'frequency': 'Monthly'},
 # ── IPI: Specialty Chemicals (SingStat Table Builder M355381:1.2.3) ──
 'singstat_ipi_specialty_chemicals': {'series_id': 'singstat_ipi_specialty_chemicals',
                                      'source': 'singstat',
                                      'source_key': 'M355381:1.2.3',
                                      'label': 'IPI: Specialty Chemicals',
                                      'unit': 'Index (2025=100)',
                                      'frequency': 'Monthly'},
 # ── Tier 5: SG Consumer Prices (CEIC, monthly) ──
 # Headline Inflation
 'ceic_cpi_yoy': {'series_id': 'ceic_cpi_yoy',
                   'source': 'ceic',
                   'source_key': '541733227',
                   'label': 'CPI All Items YoY',
                   'unit': '% YoY',
                   'frequency': 'Monthly'},
 'ceic_cpi_mom': {'series_id': 'ceic_cpi_mom',
                   'source': 'ceic',
                   'source_key': '541733457',
                   'label': 'CPI All Items MoM',
                   'unit': '% MoM',
                   'frequency': 'Monthly'},
 'ceic_mas_core_inflation': {'series_id': 'ceic_mas_core_inflation',
                              'source': 'ceic',
                              'source_key': '541733617',
                              'label': 'MAS Core Inflation YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 # Level index — pulled so we can derive MoM (MAS doesn't publish MoM directly).
 'ceic_mas_core_inflation_index': {'series_id': 'ceic_mas_core_inflation_index',
                                    'source': 'ceic',
                                    'source_key': '541733607',
                                    'label': 'MAS Core Inflation Index',
                                    'unit': '2024=100',
                                    'frequency': 'Monthly'},
 # Derived MoM — recomputed by src/derived_series.compute_mas_core_mom() after
 # each CEIC pull. source='derived' means no fetcher targets it directly.
 'mas_core_inflation_mom': {'series_id': 'mas_core_inflation_mom',
                             'source': 'derived',
                             'source_key': 'compute_from:ceic_mas_core_inflation_index',
                             'label': 'MAS Core Inflation MoM',
                             'unit': '% MoM',
                             'frequency': 'Monthly'},
 # Domestic Supply Prices
 'ceic_dspi_non_oil': {'series_id': 'ceic_dspi_non_oil',
                        'source': 'ceic',
                        'source_key': '522376457',
                        'label': 'Domestic Supply Price Index (Non-oil)',
                        'unit': 'Index',
                        'frequency': 'Monthly'},
 'ceic_dspi_oil': {'series_id': 'ceic_dspi_oil',
                    'source': 'ceic',
                    'source_key': '522376397',
                    'label': 'Domestic Supply Price Index (Oil)',
                    'unit': 'Index',
                    'frequency': 'Monthly'},
 # Producer Prices
 'ceic_mppi_non_oil': {'series_id': 'ceic_mppi_non_oil',
                        'source': 'ceic',
                        'source_key': '522377517',
                        'label': 'Manufactured Producers Price Index (Non-oil)',
                        'unit': 'Index',
                        'frequency': 'Monthly'},
 'ceic_mppi_oil': {'series_id': 'ceic_mppi_oil',
                    'source': 'ceic',
                    'source_key': '522377457',
                    'label': 'Manufactured Producers Price Index (Oil)',
                    'unit': 'Index',
                    'frequency': 'Monthly'},
 # Import Prices
 'ceic_ipi_non_oil': {'series_id': 'ceic_ipi_non_oil',
                       'source': 'ceic',
                       'source_key': '522375197',
                       'label': 'Import Price Index (Non-oil)',
                       'unit': 'Index',
                       'frequency': 'Monthly'},
 'ceic_ipi_oil': {'series_id': 'ceic_ipi_oil',
                   'source': 'ceic',
                   'source_key': '522375137',
                   'label': 'Import Price Index (Oil)',
                   'unit': 'Index',
                   'frequency': 'Monthly'},
 'ceic_ipi_food': {'series_id': 'ceic_ipi_food',
                    'source': 'ceic',
                    'source_key': '522375107',
                    'label': 'Import Price Index (Food & Live Animals)',
                    'unit': 'Index',
                    'frequency': 'Monthly'},
 # Export Prices
 'ceic_epi_non_oil': {'series_id': 'ceic_epi_non_oil',
                       'source': 'ceic',
                       'source_key': '522375307',
                       'label': 'Export Price Index (Non-oil)',
                       'unit': 'Index',
                       'frequency': 'Monthly'},
 'ceic_epi_oil': {'series_id': 'ceic_epi_oil',
                   'source': 'ceic',
                   'source_key': '522375247',
                   'label': 'Export Price Index (Oil)',
                   'unit': 'Index',
                   'frequency': 'Monthly'},
 # ── New CEIC series for previously empty nodes ──
 # Fertilisers — IMF Primary Commodity Price: Urea, US Gulf (monthly, USD/Short Ton)
 'ceic_urea_us_gulf': {'series_id': 'ceic_urea_us_gulf',
                        'source': 'ceic',
                        'source_key': '508347667',
                        'label': 'Urea Price: US Gulf (IMF)',
                        'unit': 'USD/Short Ton',
                        'frequency': 'Monthly'},
 # Real Estate — URA Property Price Index: Private Residential (quarterly)
 'ceic_property_price_index': {'series_id': 'ceic_property_price_index',
                                'source': 'ceic',
                                'source_key': '367030267',
                                'label': 'Property Price Index: Private Residential (URA)',
                                'unit': '1Q2009=100',
                                'frequency': 'Quarterly'},
 # Real Estate — URA Residential Property Transactions: Total Deals (monthly)
 'ceic_residential_transactions': {'series_id': 'ceic_residential_transactions',
                                    'source': 'ceic',
                                    'source_key': '36091201',
                                    'label': 'Residential Property Transactions: Deals (URA)',
                                    'unit': 'Unit',
                                    'frequency': 'Monthly'},

 # ════════════════════════════════════════════════════════════════════════
 # REGIONAL — CPI Headline (YoY) and CPI Core (YoY)
 # 10 countries: China, India, Indonesia, Japan, Malaysia, Philippines,
 # South Korea, Taiwan, Thailand, Vietnam. CEIC ids sourced from
 # economists' Indicators_28Apr2026.xlsx workbook.
 # ════════════════════════════════════════════════════════════════════════

 # ── Headline CPI (YoY) ──
 'regional_cpi_headline_cn': {'series_id': 'regional_cpi_headline_cn',
                              'source': 'ceic',
                              'source_key': '249097301',
                              'label': 'China CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_in': {'series_id': 'regional_cpi_headline_in',
                              'source': 'ceic',
                              'source_key': '229349002',
                              'label': 'India CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_id': {'series_id': 'regional_cpi_headline_id',
                              'source': 'ceic',
                              'source_key': '249445601',
                              'label': 'Indonesia CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_jp': {'series_id': 'regional_cpi_headline_jp',
                              'source': 'ceic',
                              'source_key': '414282577',
                              'label': 'Japan CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_my': {'series_id': 'regional_cpi_headline_my',
                              'source': 'ceic',
                              'source_key': '208964602',
                              'label': 'Malaysia CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_ph': {'series_id': 'regional_cpi_headline_ph',
                              'source': 'ceic',
                              'source_key': '249414101',
                              'label': 'Philippines CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_kr': {'series_id': 'regional_cpi_headline_kr',
                              'source': 'ceic',
                              'source_key': '208819402',
                              'label': 'South Korea CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_tw': {'series_id': 'regional_cpi_headline_tw',
                              'source': 'ceic',
                              'source_key': '414282637',
                              'label': 'Taiwan CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_th': {'series_id': 'regional_cpi_headline_th',
                              'source': 'ceic',
                              'source_key': '249410901',
                              'label': 'Thailand CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},
 'regional_cpi_headline_vn': {'series_id': 'regional_cpi_headline_vn',
                              'source': 'ceic',
                              'source_key': '366760507',
                              'label': 'Vietnam CPI Headline YoY',
                              'unit': '% YoY',
                              'frequency': 'Monthly'},

 # ── Core CPI (YoY) ──
 'regional_cpi_core_cn': {'series_id': 'regional_cpi_core_cn',
                          'source': 'ceic',
                          'source_key': '384050647',
                          'label': 'China CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_in': {'series_id': 'regional_cpi_core_in',
                          'source': 'ceic',
                          'source_key': '384078367',
                          'label': 'India CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_id': {'series_id': 'regional_cpi_core_id',
                          'source': 'ceic',
                          'source_key': '384078457',
                          'label': 'Indonesia CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_jp': {'series_id': 'regional_cpi_core_jp',
                          'source': 'ceic',
                          'source_key': '414308807',
                          'label': 'Japan CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_my': {'series_id': 'regional_cpi_core_my',
                          'source': 'ceic',
                          'source_key': '384094647',
                          'label': 'Malaysia CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_ph': {'series_id': 'regional_cpi_core_ph',
                          'source': 'ceic',
                          'source_key': '384097407',
                          'label': 'Philippines CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_kr': {'series_id': 'regional_cpi_core_kr',
                          'source': 'ceic',
                          'source_key': '384081547',
                          'label': 'South Korea CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_tw': {'series_id': 'regional_cpi_core_tw',
                          'source': 'ceic',
                          'source_key': '384114727',
                          'label': 'Taiwan CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_th': {'series_id': 'regional_cpi_core_th',
                          'source': 'ceic',
                          'source_key': '384123057',
                          'label': 'Thailand CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},
 'regional_cpi_core_vn': {'series_id': 'regional_cpi_core_vn',
                          'source': 'ceic',
                          'source_key': '384125217',
                          'label': 'Vietnam CPI Core YoY',
                          'unit': '% YoY',
                          'frequency': 'Monthly'},

 # ════════════════════════════════════════════════════════════════════════
 # REGIONAL — Industrial Production / Activity Indices (monthly)
 # Each country's official IPI series; bases vary (noted in unit string).
 # CEIC ids sourced from economists' Indicators_28Apr2026.xlsx workbook.
 # ════════════════════════════════════════════════════════════════════════
 'regional_ipi_cn': {'series_id': 'regional_ipi_cn',
                     'source': 'ceic',
                     'source_key': '371937157',
                     'label': 'China Industrial Production Index',
                     'unit': 'Index (2010=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_in': {'series_id': 'regional_ipi_in',
                     'source': 'ceic',
                     'source_key': '386587797',
                     'label': 'India Industrial Production Index',
                     'unit': 'Index (2011-12=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_id': {'series_id': 'regional_ipi_id',
                     'source': 'ceic',
                     'source_key': '322957602',
                     'label': 'Indonesia Industrial Production Index',
                     'unit': 'Index (2010=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_jp': {'series_id': 'regional_ipi_jp',
                     'source': 'ceic',
                     'source_key': '508465317',
                     'label': 'Japan Mining & Manufacturing Production Index',
                     'unit': 'Index (2020=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_my': {'series_id': 'regional_ipi_my',
                     'source': 'ceic',
                     'source_key': '402561157',
                     'label': 'Malaysia Industrial Production Index',
                     'unit': 'Index (2015=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_ph': {'series_id': 'regional_ipi_ph',
                     'source': 'ceic',
                     'source_key': '458913927',
                     'label': 'Philippines Industrial Production Volume Index',
                     'unit': 'Index (2018=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_kr': {'series_id': 'regional_ipi_kr',
                     'source': 'ceic',
                     'source_key': '505286737',
                     'label': 'South Korea All Industry Production Index',
                     'unit': 'Index (2020=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_tw': {'series_id': 'regional_ipi_tw',
                     'source': 'ceic',
                     'source_key': '508241517',
                     'label': 'Taiwan Industrial Production Index',
                     'unit': 'Index (2021=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_th': {'series_id': 'regional_ipi_th',
                     'source': 'ceic',
                     'source_key': '522375327',
                     'label': 'Thailand Value Added Production Index',
                     'unit': 'Index (2021=100)',
                     'frequency': 'Monthly'},
 'regional_ipi_vn': {'series_id': 'regional_ipi_vn',
                     'source': 'ceic',
                     'source_key': '389657597',
                     'label': 'Vietnam Industrial Production Index',
                     'unit': 'Index (2015=100)',
                     'frequency': 'Monthly'},
}
